grafana:
  replicas: 1

prometheus:
  prometheusSpec:
    replicas: 1

alertmanager:
  enabled: false

kubeEtcd:
  enabled: false

kubeScheduler:
  enabled: false

kubeControllerManager:
  enabled: false

prometheus-node-exporter:
  enabled: true

kube-state-metrics:
  enabled: true